/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dssh_Terminal */

#ifndef _Included_dssh_Terminal
#define _Included_dssh_Terminal
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_dssh_Terminal_initConsole (JNIEnv *, jobject);
// JNIEXPORT jbyte JNICALL Java_dssh_Terminal_getCh (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_dssh_Terminal_finishConsole (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_dssh_Terminal_getWsRow (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_dssh_Terminal_getWsCol (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_dssh_Terminal_getWsXPixel (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_dssh_Terminal_getWsYPixel (JNIEnv *, jobject);
JNIEXPORT jboolean JNICALL Java_dssh_Terminal_shouldChangeWindowSize (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
