#!/bin/sh
mkdir -p ~/.dssh
keytool -genkey -alias agent -keyalg RSA -validity 1024 -keystore ~/.dssh/keystore -dname "CN=dssh-agent, OU=Digmia SnakeOil, O=Digmia, L=Bratislava, S=Slovakia, C=SK" -storepass "123456" -keypass "123456"
chmod 600 ~/.dssh/keystore
